### ISSUE TITLE
Where is exactly the part where the model is deployed on the web?

### ISSUE THREAD

**Issue by jaircastruita** [PacktPublishing/Hands-On-Recommendation-Systems-with-Python#1]
"All the recommenders we've built so far reside only inside our Jupyter Notebooks. In the next chapter, we will learn how to deploy our models to the web, where they can be used by anyone on the internet."

Nonetheless, great book by the way!.

**Comment by rounakbanik** [comment]
@jaircastruita This is a printing error. The original draft of the book contained a chapter on recommender models deployed to the web but we chose to remove it since it deviated from the core material and had prerequisites that we didn't want to impose on our readers.

This particular sentence was supposed to be removed. I will ensure that this happens in subsequent editions. Apologies for the inconvenience.
